name: Deploy to Heroku

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: gkaiser77/car-eval-model:latest

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Verify Heroku CLI Installation
      run: heroku --version

    - name: Log in to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
        heroku container:login

    - name: Deploy to Heroku
      run: |
        heroku container:login
        heroku container:push web --app ana680-final-project
        heroku container:release web --app ana680-final-project

